version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstackS3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - GATEWAY_LISTEN=0.0.0.0:4566
    volumes:
      - "./localstack_data:/docker-entrypoint-initaws.d"
  dados_saude_db:
    image: postgres
    hostname: dados_saude_db
    container_name: dados_saude_db
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dados_saude_db
    volumes:
      - dados_saude_db_data:/var/lib/postgresql/data

volumes:
  dados_saude_db_data:
    driver: local
  localstack_data:
    driver: local